### ISSUE TITLE
AttributeError: 'numpy.timedelta64' object has no attribute 'total_seconds'

### ISSUE THREAD

**Issue by zseebrz** [process-intelligence-solutions/pm4py#251]
After upgrading to version 2.2.11.1 from 2.2.10.2, and running dfg discovery for performance:
dfg_perf = dfg_discovery.apply(log, parameters=parameters, variant=dfg_discovery.Variants.PERFORMANCE)

I get the following error message:

File "(...)pm4py/algo/discovery/dfg/variants/performance.py", line 92, in <listcomp> for i in range(1, len(t))]), log)
AttributeError: 'numpy.timedelta64' object has no attribute 'total_seconds'

Reverting back to version 2.2.10.2 removes the error.

I suspect the culprit is the required numpy version. For both 2.2.10.2 and 2.2.11.1 the requirement is numpy!=1.19.4. In my case 2.2.10.2 runs fine on numpy 1.18.5, but I get the above error for the latest pm4py version.

**Comment by fit-alessandro-berti** [comment]
Dear zseebrz,

I managed to reproduce your error importing a Parquet file (exported using Pyarrow).

Actually, we will force some more updated requirements from the next release (Numpy >= 1.19.5 and Pandas >= 1.1.5). I think it would also be safe to update the Pyarrow version in your installation to 5.0.0, as it is also a part of the problem. Parquet files exported starting from Pandas >= 1.1.5 using Pyarrow 5.0.0 do not have this problem when imported back.

**Comment by fit-alessandro-berti** [comment]
Dear zseebrz,

in the current release (2.2.12), we set up the aforementioned versions for the requirements. Have a nice day.
